/**
 * Generated by tools/build-palette.mjs — do not edit by hand.
 *
 * The colour measured out of every photograph: its five dominant tones
 * darkest to lightest, which family the film's cast belongs to, and the
 * mean saturation and lightness. Nothing here is chosen; it is all read
 * off the scans.
 */
export const FAMILIES = [
  {
    "id": "mono",
    "title": "Black & white",
    "note": "No colour on the roll at all."
  },
  {
    "id": "green",
    "title": "Green cast",
    "note": "What the leaked and expired rolls came back as."
  },
  {
    "id": "cyan",
    "title": "Cyan",
    "note": "Skies, glass, cold afternoons."
  },
  {
    "id": "amber",
    "title": "Amber",
    "note": "Red leaks, gold light, warm rooms."
  }
];

export const PALETTE = {
  'images/latent-01.jpg': { family: 'green', sat: 0.312, lig: 0.232, swatches: ['#343e26', '#4e4026', '#355570', '#844128', '#da4028'] },
  'images/latent-03.jpg': { family: 'green', sat: 0.367, lig: 0.176, swatches: ['#303215', '#38382a', '#4f3316', '#3a4146', '#356188'] },
  'images/latent-04.jpg': { family: 'amber', sat: 0.388, lig: 0.169, swatches: ['#353217', '#423420', '#3e3e46', '#2e7a94', '#f46f6f'] },
  'images/latent-05.jpg': { family: 'amber', sat: 0.233, lig: 0.363, swatches: ['#46624b', '#606248', '#7f6046', '#487694', '#a86146'] },
  'images/latent-07.jpg': { family: 'amber', sat: 0.355, lig: 0.553, swatches: ['#232526', '#c86230', '#709fa9', '#cecdb6', '#edf7f4'] },
  'images/sitters-01.jpg': { family: 'mono', sat: 0, lig: 0.731, swatches: ['#121212', '#7c7c7c', '#bcbcbc', '#d9d9d9', '#e8e8e8'] },
  'images/sitters-02.jpg': { family: 'mono', sat: 0, lig: 0.675, swatches: ['#1f1f1f', '#636363', '#9d9d9d', '#cfcfcf', '#efefef'] },
  'images/sitters-03.jpg': { family: 'mono', sat: 0, lig: 0.317, swatches: ['#1a1a1a', '#363636', '#5b5b5b', '#8e8e8e', '#e0e0e0'] },
  'images/sitters-04.jpg': { family: 'mono', sat: 0.091, lig: 0.565, swatches: ['#1f2020', '#6a6960', '#949189', '#a8a7a5', '#bcbab6'] },
  'images/sitters-05.jpg': { family: 'amber', sat: 0.523, lig: 0.341, swatches: ['#1e0e05', '#55351d', '#7b5837', '#b79369', '#e7d4b4'] },
  'images/sitters-06.jpg': { family: 'amber', sat: 0.151, lig: 0.428, swatches: ['#181513', '#46413a', '#776b58', '#ac997e', '#d8d6ca'] },
  'images/sitters-07.jpg': { family: 'cyan', sat: 0.22, lig: 0.527, swatches: ['#27291d', '#515661', '#758794', '#9cb5b6', '#c2dccf'] },
  'images/sitters-08.jpg': { family: 'mono', sat: 0, lig: 0.59, swatches: ['#111111', '#686868', '#9c9c9c', '#c0c0c0', '#d7d7d7'] },
  'images/sitters-09.jpg': { family: 'cyan', sat: 0.266, lig: 0.193, swatches: ['#010102', '#271829', '#464b5f', '#367aae', '#b9a9a1'] },
  'images/sitters-10.jpg': { family: 'mono', sat: 0, lig: 0.531, swatches: ['#060606', '#4b4b4b', '#929292', '#c4c4c4', '#f3f3f3'] },
  'images/sitters-11.jpg': { family: 'amber', sat: 0.278, lig: 0.454, swatches: ['#3e3028', '#674e3f', '#8b7463', '#ab9383', '#d8b795'] },
  'images/sitters-12.jpg': { family: 'mono', sat: 0, lig: 0.469, swatches: ['#272727', '#4f4f4f', '#757575', '#9a9a9a', '#bfbfbf'] },
  'images/concrete-01.jpg': { family: 'cyan', sat: 0.182, lig: 0.545, swatches: ['#35484a', '#5c7775', '#7f9c97', '#9ebdb8', '#b9d7d3'] },
  'images/concrete-02.jpg': { family: 'mono', sat: 0, lig: 0.591, swatches: ['#111111', '#565656', '#767676', '#b4b4b4', '#e5e5e5'] },
  'images/concrete-03.jpg': { family: 'mono', sat: 0, lig: 0.341, swatches: ['#222222', '#3a3a3a', '#5e5e5e', '#8b8b8b', '#dedede'] },
  'images/concrete-04.jpg': { family: 'cyan', sat: 0.357, lig: 0.397, swatches: ['#252730', '#36587d', '#406489', '#4c7196', '#c1cfce'] },
  'images/concrete-05.jpg': { family: 'mono', sat: 0.09, lig: 0.192, swatches: ['#090908', '#1e1f1d', '#464742', '#74756e', '#cbcac3'] },
  'images/concrete-06.jpg': { family: 'mono', sat: 0, lig: 0.482, swatches: ['#202020', '#4b4b4b', '#717171', '#9a9a9a', '#c9c9c9'] },
  'images/concrete-07.jpg': { family: 'cyan', sat: 0.469, lig: 0.438, swatches: ['#2b2a18', '#735c51', '#169ec1', '#23aec5', '#cfb9a8'] },
  'images/concrete-08.jpg': { family: 'cyan', sat: 0.269, lig: 0.656, swatches: ['#49362d', '#7c766b', '#a5b9c0', '#b2c8d2', '#bbd2df'] },
  'images/still-01.jpg': { family: 'green', sat: 0.215, lig: 0.831, swatches: ['#c5ab10', '#d2d7c9', '#f1e368', '#dadfd2', '#e2e6d9'] },
  'images/still-02.jpg': { family: 'mono', sat: 0, lig: 0.57, swatches: ['#232323', '#606060', '#8e8e8e', '#aeaeae', '#bababa'] },
  'images/still-03.jpg': { family: 'mono', sat: 0, lig: 0.43, swatches: ['#141414', '#383838', '#6e6e6e', '#a2a2a2', '#bababa'] },
  'images/still-04.jpg': { family: 'mono', sat: 0, lig: 0.628, swatches: ['#333333', '#666666', '#989898', '#c1c1c1', '#cfcfcf'] },
  'images/still-05.jpg': { family: 'amber', sat: 0.352, lig: 0.291, swatches: ['#2a1a13', '#4e3728', '#744930', '#8d6e4e', '#b39e74'] },
  'images/winter-01.jpg': { family: 'mono', sat: 0, lig: 0.567, swatches: ['#2b2b2b', '#636363', '#8d8d8d', '#b2b2b2', '#d8d8d8'] },
  'images/winter-02.jpg': { family: 'mono', sat: 0, lig: 0.562, swatches: ['#393939', '#5f5f5f', '#929292', '#c4c4c4', '#e0e0e0'] },
  'images/winter-03.jpg': { family: 'mono', sat: 0, lig: 0.337, swatches: ['#1e1e1e', '#383838', '#5e5e5e', '#929292', '#c6c6c6'] },
  'images/winter-04.jpg': { family: 'mono', sat: 0, lig: 0.234, swatches: ['#181818', '#2c2c2c', '#4f4f4f', '#7d7d7d', '#b9b9b9'] },
  'images/winter-06.jpg': { family: 'mono', sat: 0, lig: 0.444, swatches: ['#121212', '#3c3c3c', '#727272', '#aaaaaa', '#e3e3e3'] },
  'images/winter-07.jpg': { family: 'mono', sat: 0, lig: 0.542, swatches: ['#242424', '#5c5c5c', '#8b8b8b', '#b2b2b2', '#dbdbdb'] },
  'images/printed-01.jpg': { family: 'green', sat: 0.208, lig: 0.826, swatches: ['#363636', '#bfbfb6', '#e7e8da', '#ebecde', '#fbfcf8'] },
  'images/printed-02.jpg': { family: 'mono', sat: 0.08, lig: 0.67, swatches: ['#2a2726', '#74716e', '#a9a5a0', '#d8d4cf', '#fdfdfc'] },
  'images/about.jpg': { family: 'mono', sat: 0, lig: 0.818, swatches: ['#363636', '#757575', '#ababab', '#dadada', '#ffffff'] },
};
