/**
 * Generated by tools/build-responsive.mjs — do not edit by hand.
 *
 * For each photograph: its real pixel size, and the widths that were
 * actually written into images/r/. The grid builds its srcset from this,
 * so it never offers the browser a file that is not there.
 */
export const SIZES = {
  "images/about.jpg": {
    "width": 1680,
    "height": 1680,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/concrete-01.jpg": {
    "width": 1334,
    "height": 868,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-02.jpg": {
    "width": 1207,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-03.jpg": {
    "width": 1306,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-04.jpg": {
    "width": 854,
    "height": 921,
    "widths": [
      480
    ]
  },
  "images/concrete-05.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-06.jpg": {
    "width": 1374,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-07.jpg": {
    "width": 1123,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/concrete-08.jpg": {
    "width": 1512,
    "height": 1002,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/hero.jpg": {
    "width": 1800,
    "height": 1193,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/latent-01.jpg": {
    "width": 1800,
    "height": 1193,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/latent-03.jpg": {
    "width": 1800,
    "height": 1193,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/latent-04.jpg": {
    "width": 1800,
    "height": 1193,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/latent-05.jpg": {
    "width": 1800,
    "height": 1193,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/latent-07.jpg": {
    "width": 1241,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/printed-01.jpg": {
    "width": 1497,
    "height": 1800,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/printed-02.jpg": {
    "width": 1800,
    "height": 1273,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/sitters-01.jpg": {
    "width": 1512,
    "height": 1002,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/sitters-02.jpg": {
    "width": 1001,
    "height": 1001,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-03.jpg": {
    "width": 970,
    "height": 990,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-04.jpg": {
    "width": 1202,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-05.jpg": {
    "width": 1800,
    "height": 1202,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/sitters-06.jpg": {
    "width": 1135,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-07.jpg": {
    "width": 1509,
    "height": 1000,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/sitters-08.jpg": {
    "width": 1193,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-09.jpg": {
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-10.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-11.jpg": {
    "width": 1202,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/sitters-12.jpg": {
    "width": 562,
    "height": 517,
    "widths": [
      480
    ]
  },
  "images/still-01.jpg": {
    "width": 1411,
    "height": 1761,
    "widths": [
      480,
      960
    ]
  },
  "images/still-02.jpg": {
    "width": 1500,
    "height": 1500,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/still-03.jpg": {
    "width": 1800,
    "height": 1103,
    "widths": [
      480,
      960,
      1440
    ]
  },
  "images/still-04.jpg": {
    "width": 924,
    "height": 1800,
    "widths": [
      480
    ]
  },
  "images/still-05.jpg": {
    "width": 1037,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/winter-01.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/winter-02.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/winter-03.jpg": {
    "width": 822,
    "height": 1512,
    "widths": [
      480
    ]
  },
  "images/winter-04.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/winter-06.jpg": {
    "width": 1350,
    "height": 1800,
    "widths": [
      480,
      960
    ]
  },
  "images/winter-07.jpg": {
    "width": 792,
    "height": 904,
    "widths": [
      480
    ]
  }
};
