/**
 * Generates js/lqip.js — a tiny blurred stand-in for every photograph.
 *
 * Each entry is a ~24px-wide JPEG as a data URI. The grid paints it behind the
 * real image so a frame arrives as a soft wash of its own colour and resolves
 * into focus, instead of snapping in from nothing. Scaling 24px up to full
 * width is what produces the blur; no filter is needed.
 *
 * Run after adding or replacing photographs:
 *   node tools/build-lqip.mjs
 */
import sharp from 'sharp';
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IMAGES = join(ROOT, 'images');

const entries = {};
for (const file of readdirSync(IMAGES).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort()) {
  const buf = await sharp(join(IMAGES, file))
    .resize(24, 24, { fit: 'inside' })
    .jpeg({ quality: 45 })
    .toBuffer();
  entries[`images/${file}`] = `data:image/jpeg;base64,${buf.toString('base64')}`;
}

const body = Object.entries(entries)
  .map(([k, v]) => `  '${k}':\n    '${v}',`)
  .join('\n');

writeFileSync(
  join(ROOT, 'js', 'lqip.js'),
  `/**\n * Generated by tools/build-lqip.mjs — do not edit by hand.\n *\n * Low-quality image placeholders: a 24px JPEG per photograph, inlined so the\n * grid can paint something in the right colours before the real file lands.\n */\nexport const LQIP = {\n${body}\n};\n`
);

console.log(`wrote js/lqip.js — ${Object.keys(entries).length} placeholders`);
